# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'IMF/pom.xml'
    goals: 'clean install cluecumber-report:reporting'
    options: '-Dbrowser="chrome_win_headless"'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'd:\a\1\s\IMF\target/generated-report/index.html'
- task: publishHtml@1
  inputs:
    artifactName: 'Regression Report'
    htmlFilePath: 'd:\a\1\s\IMF\target/generated-report/index.html'

