# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'IMF/pom.xml'
    goals: 'clean install cluecumber-report:reporting'
    options: 'browser="chrome_linux_headless"'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: publishHtml@1
  inputs:
    artifactName: 'Regression Report'
    htmlFilePath: '/home/vsts/work/1/s/IMF/target/generated-report/index.html'